#pragma once
#include <array>
std::array healthy_messages {
    "Hey! Is that a train?",
    "Choo Choo! Here comes the train!",
    "All aboard the C++ express!",
    "Next stop: Terminal Station",
    "Watch out for the train!",
    "Toot Toot! The train is coming through!",
    "The train is burning C++ coal rn",
    "Sorry, I kinda forgot what to say here?",
    "Who cares bro?",
    "Shout out to women",
    "Love me some twitter, Or dare I say X",
    "I have spent an absurd amount of time on this",
    "Damn look at them smooth jiggle physics",
    "I will personally crash this train in your house",
    "This train is powered by your CPU",
    "This train runs on the famous '                 ' engine!",
    "Next stop: Your house",
    "This train is faster than your internet connection",
    "C++: Making trains run since 1998",
    "This train has more lines of garbage than your trashbag",
    "THE UPDATED SL: THE JOURNEY",
    "SL: The journey edition",
    "SL: The coal train edition",
    "SL: The coal train update",
    "SL: The classic era",
    "Hello, I just wanted to ask. How are you doing today?",
    "To train or not to train. That's the question",
    "I'm terribly disappointed. Who wouldve thought?",
    "skibidi toiet da rizz man cuase   im a 2 yer old kid",
    "SKIBIDI TOILET: THE LOOKSMAX EDITION",
    "Brainrot, The story",
    "This train has more stories than your entire life",
    "Geniunely, Who cares?",
    "I'm done writing messages",
    "I'm quitting",
    "Look at them trains",
    "ngl im deadass tired frfr no cap",
    "ngl im craving some IRL macdonalds frfr",
    "Did you know: 'give your Fanum tax. Or IRS will come after you. Don't try me'"
};